<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>

    <section name="Saga.Manager.NetworkSettings" type="Saga.Configuration.NetworkSettings, Saga.Authentication" />
    <section name="Saga.Manager.Database" type="Saga.Configuration.DatabaseSettings, Saga.Authentication" />
  </configSections>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="delimited" type="System.Diagnostics.DelimitedListTraceListener" initializeData="authentication.log.csv" traceOutputOptions="DateTime" delimiter="," />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
  <runtime>
    <legacyUnhandledExceptionPolicy enabled="1" />
  </runtime>

  <!-- Network Settings -->
  <Saga.Manager.NetworkSettings>
    <Connections>
      <add connection="public" host="0.0.0.0" port="64000" />
      <add connection="internal" host="0.0.0.0" port="64002" />
    </Connections>
  </Saga.Manager.NetworkSettings>

  <!-- Structurize all default paths -->
  <Saga.Manager.Database
      host="127.0.0.1"
      username="root"
      password="root"
      port="3306"
      database="sagarev"
      provider="Saga.Authentication.Data.Mysql.dll, Saga.Authentication.Data.Mysql.MysqlProvider" />
</configuration>